### PR TITLE
Download annoyance

### PR DESCRIPTION
**Pull request by Derro8**
This makes it so instead of returning to the main menu after downloading a mod, you'll return to the game's mod list on the page you were on instead.

### CODE REVIEW

**Comment by PoloNX** [comment]
It's a good feature. Thanks

**Comment by PoloNX** [comment]
I can't test it but if you're on page n and you download the mod. You will go to page n or page 1 ?

**Comment by Derro8** [comment]
>Yea if you download a mod on page 1 you'll return to page 1

**Comment by PoloNX** [comment]
@Derro8 there is one issue when you search one mod with the name

**Pull request merged**
