### PR TITLE
Greek translation

### PR DESCRIPTION
**Pull request by spkats1**
Greek translation

### CODE REVIEW

**Comment by PoloNX** [comment]
Hi, which is the better between #8 and #9 ?

**Comment by PoloNX** [comment]
Merged #8

**Comment by spkats1** [comment]
#8 came on GitHub first so merge this. Once a release is made, I will check everything on the app and then submit a new pull request for #9 (if changes are more grammatically accurate).

**Comment by PoloNX** [comment]
Okay thanks !

**Pull request closed without merging**
